#!/bin/bash

# Update the package list to ensure you have the latest information
sudo yum update -y

# Install Nginx using yum
sudo yum install nginx -y

# Start the Nginx service
sudo systemctl start nginx
